# Generated by Django 5.1.2 on 2024-10-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_country_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostolicinformation',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apostolicinformation',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
