# Generated by Django 5.0.6 on 2024-07-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('social_service', 'Social Service'), ('pastoral', 'Pastoral'), ('mission', 'Mission')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('established_year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
