# Generated by Django 5.1.2 on 2024-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='news_pdfs/'),
        ),
    ]
