# Generated by Django 5.1.2 on 2024-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_newspost_image_newspost_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='pdf',
        ),
        migrations.AddField(
            model_name='newspost',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
