# Generated by Django 5.1.2 on 2024-10-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_remove_newspost_image_remove_newspost_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='attachment',
        ),
    ]
