# Generated by Django 5.1.2 on 2024-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_search_delete_distances_delete_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ministry_type', models.CharField(choices=[('SCH', 'School'), ('TSC', 'Technical School'), ('HST', 'Hostel'), ('RHB', 'Rehabilitation Center'), ('FRM', 'Formation House'), ('ASH', 'Ashram'), ('OTH', 'Other')], max_length=3)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
