# Generated by Django 5.1.2 on 2024-10-19 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_emails', models.BooleanField(default=True)),
                ('receive_public_greetings', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_type', models.CharField(choices=[('birthday', 'Birthday'), ('first_profession', 'First Profession'), ('final_profession', 'Final Profession')], max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'greeting_type', 'date'], name='greetings_g_user_id_45b237_idx')],
            },
        ),
    ]
