# Generated by Django 5.0.7 on 2024-07-25 05:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240715_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
