# Generated by Django 5.0.7 on 2024-07-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_province_administration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='province_photos/')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Province_Administration',
        ),
    ]
