# Generated by Django 5.1.2 on 2024-10-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_teammember_delete_provinceadministration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='schools',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
