# Generated by Django 5.1.2 on 2024-10-24 11:39

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('new_appointment', 'New Appointment'), ('transfer', 'Transfer'), ('promotion', 'Promotion'), ('extension', 'Extension')], max_length=20)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='appointment_headers/')),
                ('salutation', models.CharField(max_length=100)),
                ('body_text', tinymce.models.HTMLField()),
                ('previous_ministry', models.CharField(blank=True, max_length=100)),
                ('new_ministry', models.CharField(max_length=100)),
                ('new_designation', models.CharField(max_length=100)),
                ('ministry_location', models.CharField(max_length=255)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('provincial_name', models.CharField(max_length=255)),
                ('provincial_designation', models.CharField(max_length=255)),
                ('footer_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField()),
                ('comments', models.TextField(blank=True)),
                ('appointment_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentletter')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentletter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
