# Generated by Django 5.1.2 on 2024-10-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('establishment_year', models.PositiveIntegerField()),
                ('ownership', models.CharField(max_length=100)),
                ('administration', models.CharField(max_length=100)),
                ('grades', models.CharField(max_length=50)),
                ('students', models.PositiveIntegerField()),
                ('teachers', models.PositiveIntegerField()),
                ('office_staff', models.PositiveIntegerField()),
                ('employees', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('short_history', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='institutions.category')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='institution_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='institutions.institution')),
            ],
        ),
    ]
