# Generated by Django 5.1.2 on 2024-10-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_number_of_directors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='institutionimage',
            options={'verbose_name': 'Institution Image', 'verbose_name_plural': 'Institution Images'},
        ),
        migrations.AlterField(
            model_name='institution',
            name='administration',
            field=models.CharField(blank=True, help_text='Administrative body responsible for the institution', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='employees',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of other employees', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='grades',
            field=models.CharField(blank=True, help_text='Grade levels offered (e.g., I-X, XI-XII)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='number_of_directors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of formation directors', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='number_of_formees',
            field=models.PositiveIntegerField(blank=True, help_text='Number of formees in the formation house', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='office_staff',
            field=models.PositiveIntegerField(blank=True, help_text='Number of office staff members', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='ownership',
            field=models.CharField(blank=True, help_text='Type of ownership (e.g., Private, Government)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='status',
            field=models.CharField(blank=True, help_text='Current status of the institution', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='students',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of students', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='teachers',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of teachers', null=True),
        ),
        migrations.AlterField(
            model_name='institutionimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the image', max_length=200),
        ),
        migrations.AlterField(
            model_name='institutionimage',
            name='image',
            field=models.ImageField(help_text='Upload an image for the institution', upload_to='institution_images/'),
        ),
    ]
